version: '3.8'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    networks:
      - storewk
  
  #db:
  #  container_name: 'mysql'
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: CatalogDb
  #    MYSQL_ROOT_PASSWORD: 081206
  #  networks: 
  #    - storewk
  

  #catalog-api:
  #  image: ${REGISTRY:-catalog}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
  #  build:
  #    context: .
  #    dockerfile: Services/Catalog/Catalog.API/Dockerfile
  #  depends_on:
  #    - db
  #    - rabbitmq

networks:
  storewk:
    driver: bridge